name: Publish

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/neck
            asset_name: neck-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/neck.exe
            asset_name: neck-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/neck
            asset_name: neck-macos

    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release --locked
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
