name: Publish

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }} with feature ${{ matrix.feature }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]
        feature: ["default", "tls"]
        include:
          - name: linux
            os: ubuntu-latest
            filename: neck
          - name: windows
            os: windows-latest
            filename: neck.exe
          - name: macos
            os: macos-latest
            filename: neck

    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release --features ${{ matrix.feature }} --locked
      - uses: actions/upload-artifact@v3
        with:
          name: neck-${{ matrix.feature }}-${{ matrix.name }}
          path: target/release/${{ matrix.fielname }}
