name: Publish

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            filename: neck
          - name: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            filename: neck.exe
          - name: macos
            os: macos-latest
            target: x86_64-apple-darwin
            filename: neck

    steps:
      - uses: actions/checkout@v3
      - if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt install -y musl-tools --no-install-recommends
          rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --locked --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: neck-${{ matrix.name }}
          path: target/${{ matrix.target }}/release/${{ matrix.filename }}
